spring:
  application:
    name: ChatAI
server:
  port: 18080
# 大模型配置，指定模型
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ur key
        model-name: qwen-max
      embedding-model:
        api-key: ur key
        model-name: text-embedding-v4
bigmodel:
  api-key: ur key
