spring:
  application:
    name: ChatAI
server:
  port: 18080
  servlet:
    context-path: /api
# 大模型配置，指定模型
# https://bailian.console.aliyun.com/?utm_content=se_1021226623&tab=model#/api-key
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ur key
        model-name: qwen-max
      embedding-model:
        api-key: ur key
        model-name: text-embedding-v4
      streaming-chat-model:
        api-key: ur key
        model-name: qwen-max
# https://www.bigmodel.cn/usercenter/proj-mgmt/apikeys
bigmodel:
  api-key: ur key
